project_id = "hpdnubbqftbsaxthlagt"

[functions.ai-search]
verify_jwt = false

[functions.ai-pdf-convert]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.word-to-pdf]
verify_jwt = false

[functions.ai-file-convert]
verify_jwt = false
