project_id = "hpdnubbqftbsaxthlagt"

[functions.ai-search]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.cloudconvert-file]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.generate-vba]
verify_jwt = false

[functions.generate-sql]
verify_jwt = false
